import { AbbreviationDefinition, DrugInteraction, EducationalInfo } from '../src/types';

export const MEDICAL_ABBREVIATIONS: AbbreviationDefinition[] = [
  {
    abbr: 'OD',
    meaning: 'Omni Die (Once Daily)',
    plainExplanation: 'Take this medicine once every day, ideally at the same time each day.',
    category: 'frequency',
  },
  {
    abbr: 'BD / BID',
    meaning: 'Bis In Die (Twice Daily)',
    plainExplanation: 'Take this medicine two times a day, usually separated by roughly 10–12 hours (e.g., morning and evening).',
    category: 'frequency',
  },
  {
    abbr: 'TDS / TID',
    meaning: 'Ter Die Sumendum / Ter In Die (Three Times Daily)',
    plainExplanation: 'Take this medicine three times a day, spaced evenly across waking hours (roughly every 6–8 hours).',
    category: 'frequency',
  },
  {
    abbr: 'QID / QDS',
    meaning: 'Quater In Die (Four Times Daily)',
    plainExplanation: 'Take this medicine four times a day (approximately every 4–6 hours). Note: "QD" is sometimes misread as "QID", so pharmacists double-check this.',
    category: 'frequency',
    ambiguous: false,
  },
  {
    abbr: 'QD',
    meaning: 'Quaque Die (Once Daily)',
    plainExplanation: 'Take once every day. (Often confused with QID, so verify whether once or four times daily was intended).',
    category: 'frequency',
    ambiguous: true,
    warningNote: 'Verify whether QD (once daily) or QID (four times daily) was intended by your doctor.',
  },
  {
    abbr: 'PRN / SOS',
    meaning: 'Pro Re Nata / Si Opus Sit (As Needed / In Emergency)',
    plainExplanation: 'Take this medicine only when symptoms occur (such as pain, fever, or nausea), within the maximum allowed daily dose.',
    category: 'condition',
  },
  {
    abbr: 'PO',
    meaning: 'Per Os (By Mouth / Orally)',
    plainExplanation: 'Swallow this medicine by mouth with water, rather than applying topically or injecting.',
    category: 'route',
  },
  {
    abbr: 'AC',
    meaning: 'Ante Cibum (Before Meals)',
    plainExplanation: 'Take this medicine before eating food (usually 30 to 60 minutes before meals).',
    category: 'timing',
  },
  {
    abbr: 'PC',
    meaning: 'Post Cibum (After Meals)',
    plainExplanation: 'Take this medicine after eating food or with a meal to enhance absorption or protect your stomach.',
    category: 'timing',
  },
  {
    abbr: 'HS / BT',
    meaning: 'Hora Somni / Bedtime',
    plainExplanation: 'Take this medicine right before sleeping at night.',
    category: 'timing',
  },
  {
    abbr: 'BBF',
    meaning: 'Before Breakfast',
    plainExplanation: 'Take 30–60 minutes before having your morning breakfast (on an empty stomach).',
    category: 'timing',
  },
  {
    abbr: 'ABF',
    meaning: 'After Breakfast',
    plainExplanation: 'Take shortly after finishing your morning breakfast.',
    category: 'timing',
  },
  {
    abbr: '1-0-1',
    meaning: 'Morning and Night (Twice Daily)',
    plainExplanation: 'Take 1 dose in the morning and 1 dose at night (12 hours apart).',
    category: 'frequency',
  },
  {
    abbr: '1-0-0',
    meaning: 'Morning Only (Once Daily)',
    plainExplanation: 'Take 1 dose in the morning only.',
    category: 'frequency',
  },
  {
    abbr: '0-0-1',
    meaning: 'Night Only (Once Daily at Bedtime)',
    plainExplanation: 'Take 1 dose at night before sleeping.',
    category: 'frequency',
  },
  {
    abbr: '0-1-0',
    meaning: 'Afternoon Only (Once Daily at Lunch)',
    plainExplanation: 'Take 1 dose in the afternoon after lunch.',
    category: 'frequency',
  },
  {
    abbr: '1-1-1',
    meaning: 'Morning, Afternoon, and Night (Three Times Daily)',
    plainExplanation: 'Take 1 dose in the morning, 1 in the afternoon, and 1 at night.',
    category: 'frequency',
  },
  {
    abbr: '1-1-1-1',
    meaning: 'Four Times Daily',
    plainExplanation: 'Take 1 dose four times spaced throughout the day.',
    category: 'frequency',
  },
  {
    abbr: '1/2-0-1/2',
    meaning: 'Half tablet Morning and Half tablet Night',
    plainExplanation: 'Split tablet and take half in the morning and half in the evening.',
    category: 'frequency',
  },
  {
    abbr: 'STAT',
    meaning: 'Statim (Immediately)',
    plainExplanation: 'Take the first dose right now without delay.',
    category: 'timing',
  },
  {
    abbr: 'Q4H / Q6H / Q8H',
    meaning: 'Quaque N Hora (Every 4 / 6 / 8 Hours)',
    plainExplanation: 'Take a dose strictly at the specified interval around the clock if instructed.',
    category: 'frequency',
  },
  {
    abbr: 'SL',
    meaning: 'Sublingual',
    plainExplanation: 'Place the tablet under your tongue to dissolve; do not swallow it whole.',
    category: 'route',
  },
  {
    abbr: 'IM',
    meaning: 'Intramuscular',
    plainExplanation: 'Administered as an injection directly into a muscle by a licensed healthcare professional.',
    category: 'route',
  },
  {
    abbr: 'IV',
    meaning: 'Intravenous',
    plainExplanation: 'Administered directly into a vein through an infusion or syringe in a clinical setting.',
    category: 'route',
  },
  {
    abbr: 'SC / SQ',
    meaning: 'Subcutaneous',
    plainExplanation: 'Injected just under the skin (commonly used for insulin or heparin).',
    category: 'route',
  },
  {
    abbr: 'TOP',
    meaning: 'Topical',
    plainExplanation: 'Apply externally on the skin surface.',
    category: 'route',
  },
  {
    abbr: 'INH',
    meaning: 'Inhalation',
    plainExplanation: 'Inhale through an inhaler, nebulizer, or spacer device.',
    category: 'route',
  },
  {
    abbr: 'GTT',
    meaning: 'Guttae (Drops)',
    plainExplanation: 'Administered as drops (for eyes, ears, or nose).',
    category: 'route',
  },
];

export interface DrugDatabaseEntry {
  genericName: string;
  brandAliases: string[];
  activeIngredients: string[];
  category: string;
  commonStrengths: string[];
  dosageForms: string[];
  commonUses: string[];
  howItWorksSimple: string;
  administrationAdvice: string;
  sideEffects: {
    common: string[];
    important: string[];
    urgent: string[];
  };
  precautions: string[];
  storage: string;
  missedDoseAdvice: string;
}

export const KNOWN_DRUG_DATABASE: Record<string, DrugDatabaseEntry> = {
  paracetamol: {
    genericName: 'Paracetamol (Acetaminophen)',
    brandAliases: ['dolo', 'dolo 650', 'crocin', 'calpol', 'panadol', 'tylenol', 'pacimol', 'feva', 'paracip', 'combiflam'],
    activeIngredients: ['Paracetamol'],
    category: 'Analgesic & Antipyretic (Pain reliever & Fever reducer)',
    commonStrengths: ['500 mg', '650 mg', '120 mg/5ml', '250 mg/5ml', '1000 mg'],
    dosageForms: ['Tablet', 'Syrup', 'Suspension', 'Suppository', 'IV Infusion'],
    commonUses: ['Mild to moderate headache, muscle aches, toothache', 'Reducing elevated body temperature (fever)', 'General pain relief'],
    howItWorksSimple: 'Works in the brain and central nervous system to block chemical messengers that signal pain and regulate body temperature.',
    administrationAdvice: 'Can be taken with or without food. Do not exceed 4,000 mg (4 grams) in any 24-hour period across all medications.',
    sideEffects: {
      common: ['Mild nausea', 'Headache (rare)'],
      important: ['Upset stomach', 'Skin itching'],
      urgent: ['Severe allergic reaction with facial swelling', 'Signs of liver stress: dark urine, yellowing of skin/eyes (jaundice), severe upper stomach pain'],
    },
    precautions: [
      'Avoid consuming alcoholic beverages while taking paracetamol.',
      'Check all other cough, cold, and flu medicines to avoid taking duplicate paracetamol.',
      'Inform your doctor if you have known liver or kidney conditions.',
    ],
    storage: 'Store at room temperature (below 25°C / 77°F) away from direct sunlight and moisture.',
    missedDoseAdvice: 'If you miss a dose, take it as soon as remembered unless it is almost time for your next scheduled dose. Never take double doses.',
  },
  amoxicillin: {
    genericName: 'Amoxicillin & Clavulanate (Augmentin)',
    brandAliases: ['augmentin', 'augmentin 625', 'mox', 'moxclav', 'clavam', 'amoxil', 'novamox', 'clavulin', 'curam'],
    activeIngredients: ['Amoxicillin', 'Clavulanic Acid (in Augmentin/Moxclav/Clavam)'],
    category: 'Penicillin-Class Antibiotic',
    commonStrengths: ['250 mg', '500 mg', '625 mg', '375 mg', '1000 mg', '228.5 mg/5ml', '457 mg/5ml'],
    dosageForms: ['Tablet', 'Capsule', 'Dry Syrup', 'Suspension', 'Injection'],
    commonUses: ['Bacterial respiratory tract infections (sinusitis, bronchitis, pneumonia)', 'Ear, nose, and throat bacterial infections', 'Urinary tract, skin, and dental infections'],
    howItWorksSimple: 'Amoxicillin stops bacterial growth by preventing bacteria from building protective cell walls; Clavulanate protects amoxicillin from bacterial enzyme breakdown.',
    administrationAdvice: 'Take at evenly spaced intervals. Taking it at the start of a meal or immediately after minimizes stomach irritation. Complete the entire prescribed course.',
    sideEffects: {
      common: ['Mild diarrhea or loose stools', 'Nausea', 'Mild stomach cramps'],
      important: ['Persistent watery diarrhea', 'Vaginal yeast discomfort', 'Mild skin rash'],
      urgent: ['Severe allergic reaction (anaphylaxis): hives, breathing difficulty, swelling of lips/throat', 'Severe colitis (frequent bloody stools, high fever)'],
    },
    precautions: [
      'Never take if you have a known penicillin, amoxicillin, or beta-lactam allergy.',
      'Always finish the entire course even if you feel completely better, to prevent bacterial resistance.',
      'May reduce effectiveness of oral contraceptive pills.',
    ],
    storage: 'Store tablets in a dry place. Reconstituted liquid suspensions must be refrigerated and discarded after 7–10 days.',
    missedDoseAdvice: 'Take as soon as remembered. If close to next dose, skip the missed dose and resume normal schedule. Do not double up.',
  },
  pantoprazole: {
    genericName: 'Pantoprazole',
    brandAliases: ['pan', 'pan 40', 'pantocid', 'pantop', 'protonix', 'pan-d', 'pantocid-dsr', 'pantop-d', 'pantocar'],
    activeIngredients: ['Pantoprazole', 'Domperidone (in Pan-D / Pantocid-DSR)'],
    category: 'Proton Pump Inhibitor (PPI / Acid Reducer)',
    commonStrengths: ['20 mg', '40 mg', '40 mg + 30 mg'],
    dosageForms: ['Enteric Coated Tablet', 'Capsule', 'IV Injection'],
    commonUses: ['Gastroesophageal reflux disease (GERD / Acid reflux / Heartburn)', 'Protection of stomach lining from painkillers/antibiotics', 'Gastric and duodenal ulcers'],
    howItWorksSimple: 'Inactivates the gastric proton pump enzymes in stomach parietal cells, dramatically lowering excessive hydrochloric acid production.',
    administrationAdvice: 'Swallow whole with a glass of water 30–60 minutes before breakfast on an empty stomach. Do not crush, chew, or split enteric-coated tablets.',
    sideEffects: {
      common: ['Mild headache', 'Flatulence or constipation', 'Mild abdominal discomfort'],
      important: ['Low magnesium symptoms (muscle cramps, tremors) with long-term use', 'Joint stiffness'],
      urgent: ['Severe persistent watery diarrhea (C. difficile concern)', 'Severe allergic rash, blistering, or facial swelling'],
    },
    precautions: [
      'Do not crush or chew enteric-coated tablets.',
      'Take consistently before morning meal for maximum therapeutic acid suppression.',
      'Long-term continuous use (over 1 year) should be evaluated periodically by a doctor for vitamin B12 and bone density.',
    ],
    storage: 'Store in a cool, dry place away from heat and moisture.',
    missedDoseAdvice: 'Take before your next meal if remembered on the same day. Do not take two doses at once.',
  },
  omeprazole: {
    genericName: 'Omeprazole',
    brandAliases: ['omez', 'omez-d', 'prilesec', 'prilosec', 'lokit', 'omizac'],
    activeIngredients: ['Omeprazole', 'Domperidone (in Omez-D)'],
    category: 'Proton Pump Inhibitor (PPI)',
    commonStrengths: ['10 mg', '20 mg', '40 mg'],
    dosageForms: ['Capsule', 'Tablet'],
    commonUses: ['Acid reflux', 'Heartburn', 'Peptic ulcer treatment'],
    howItWorksSimple: 'Reduces the amount of acid produced in your stomach by blocking proton pumps.',
    administrationAdvice: 'Take once daily before breakfast with water. Swallow capsule whole.',
    sideEffects: {
      common: ['Headache', 'Mild diarrhea or constipation', 'Stomach ache'],
      important: ['Persistent stomach pain'],
      urgent: ['Severe diarrhea with fever', 'Allergic reaction with rash and facial swelling'],
    },
    precautions: ['Do not crush or chew capsules.', 'May interact with blood thinners like Clopidogrel.'],
    storage: 'Store in original packaging at room temperature.',
    missedDoseAdvice: 'Take as soon as remembered before meals, or skip if next dose is due.',
  },
  rabeprazole: {
    genericName: 'Rabeprazole',
    brandAliases: ['razo', 'razo-d', 'veloz', 'rabicip', 'aciphex', 'rabemac'],
    activeIngredients: ['Rabeprazole', 'Domperidone (in Razo-D / Veloz-D)'],
    category: 'Proton Pump Inhibitor (PPI)',
    commonStrengths: ['20 mg', '20 mg + 30 mg'],
    dosageForms: ['Enteric Coated Tablet'],
    commonUses: ['Severe acid reflux', 'Heartburn', 'Ulcer healing'],
    howItWorksSimple: 'Rapidly blocks acid secretion in the stomach to allow esophagus and stomach lining to heal.',
    administrationAdvice: 'Take 30 minutes before breakfast with a full glass of water.',
    sideEffects: {
      common: ['Headache', 'Nausea', 'Gas / bloating'],
      important: ['Dizziness', 'Muscle pain'],
      urgent: ['Severe watery diarrhea', 'Skin rash or blistering'],
    },
    precautions: ['Swallow whole without chewing.'],
    storage: 'Store in cool and dry conditions below 25°C.',
    missedDoseAdvice: 'Take before the next meal if remembered.',
  },
  ibuprofen: {
    genericName: 'Ibuprofen',
    brandAliases: ['advil', 'motrin', 'brufen', 'nurofen', 'combiflam', 'ibugesic'],
    activeIngredients: ['Ibuprofen'],
    category: 'Non-Steroidal Anti-Inflammatory Drug (NSAID)',
    commonStrengths: ['200 mg', '400 mg', '600 mg', '800 mg', '100 mg/5ml'],
    dosageForms: ['Tablet', 'Capsule', 'Syrup', 'Gel'],
    commonUses: ['Inflammatory pain relief (joints, dental, menstrual, muscular)', 'Swelling reduction', 'Fever reduction'],
    howItWorksSimple: 'Inhibits COX-1 and COX-2 enzymes to decrease pain- and inflammation-causing prostaglandins.',
    administrationAdvice: 'Always take with food, milk, or immediately after a meal with plenty of water to protect your stomach.',
    sideEffects: {
      common: ['Mild indigestion', 'Heartburn', 'Nausea'],
      important: ['Swelling in legs', 'Elevated blood pressure', 'Ringing in ears'],
      urgent: ['Stomach bleeding (black tarry stools, vomiting dark material)', 'Sudden shortness of breath, chest pain, or severe allergic swelling'],
    },
    precautions: [
      'Avoid if you have active stomach ulcers, severe kidney disease, or severe heart failure.',
      'Do not combine with other NSAIDs (such as naproxen or diclofenac) without doctor supervision.',
      'Avoid during the third trimester of pregnancy.',
    ],
    storage: 'Store below 25°C away from heat and moisture.',
    missedDoseAdvice: 'Take when needed with food, maintaining at least 6 hours between doses.',
  },
  aceclofenac: {
    genericName: 'Aceclofenac',
    brandAliases: ['zerodol', 'zerodol-p', 'zerodol-sp', 'hifenac', 'hifenac-p', 'hifenac-sp', 'aceclo', 'dolowin'],
    activeIngredients: ['Aceclofenac', 'Paracetamol (in Zerodol-P)', 'Serratiopeptidase (in Zerodol-SP)'],
    category: 'NSAID & Anti-inflammatory Complex',
    commonStrengths: ['100 mg', '100 mg + 325 mg', '100 mg + 325 mg + 15 mg'],
    dosageForms: ['Tablet'],
    commonUses: ['Post-surgical dental/orthopedic pain', 'Osteoarthritis and rheumatoid joint pain', 'Acute musculoskeletal inflammation'],
    howItWorksSimple: 'Inhibits inflammatory cytokines and prostaglandin synthesis to reduce painful swelling.',
    administrationAdvice: 'Take strictly after meals with water. Do not take on an empty stomach.',
    sideEffects: {
      common: ['Gastric discomfort', 'Nausea', 'Dizziness'],
      important: ['Acid indigestion', 'Abdominal cramps'],
      urgent: ['Dark tarry stools (gastric bleeding)', 'Severe skin reactions / facial swelling'],
    },
    precautions: ['Always take after food.', 'Avoid combining with other painkillers containing paracetamol or NSAIDs.'],
    storage: 'Store in original blister pack at room temperature.',
    missedDoseAdvice: 'Take after your next meal if needed. Do not double up.',
  },
  diclofenac: {
    genericName: 'Diclofenac',
    brandAliases: ['voveran', 'voveran-sr', 'voltaren', 'dynapar', 'diclogel', 'cataflam'],
    activeIngredients: ['Diclofenac Sodium / Potassium'],
    category: 'Potent Non-Steroidal Anti-Inflammatory Drug (NSAID)',
    commonStrengths: ['50 mg', '75 mg', '100 mg', '1% Gel', '75 mg/ml Injection'],
    dosageForms: ['Tablet', 'SR Tablet', 'Gel', 'Injection', 'Suppository'],
    commonUses: ['Acute muscular sprains', 'Severe arthritis pain', 'Renal colic / post-op pain'],
    howItWorksSimple: 'Strong anti-inflammatory that rapidly inhibits COX enzymes to resolve inflammatory pain and swelling.',
    administrationAdvice: 'Take with or after food. Swallow sustained-release tablets whole.',
    sideEffects: {
      common: ['Epigastric pain', 'Heartburn', 'Nausea'],
      important: ['Water retention / swelling', 'Elevated BP'],
      urgent: ['Gastrointestinal ulceration / bleeding', 'Severe allergic reaction'],
    },
    precautions: ['Take strictly with meals or antacid protection.', 'Use shortest duration necessary.'],
    storage: 'Store in dry place below 30°C.',
    missedDoseAdvice: 'Take after next meal if pain persists.',
  },
  azithromycin: {
    genericName: 'Azithromycin',
    brandAliases: ['azithral', 'azee', 'zithromax', 'zady', 'azicip', 'z-pack'],
    activeIngredients: ['Azithromycin'],
    category: 'Macrolide Antibiotic',
    commonStrengths: ['250 mg', '500 mg', '100 mg/5ml', '200 mg/5ml'],
    dosageForms: ['Tablet', 'Capsule', 'Suspension', 'IV Infusion'],
    commonUses: ['Bacterial respiratory infections (bronchitis, pneumonia, sinusitis)', 'Tonsillitis, strep throat', 'Skin infections'],
    howItWorksSimple: 'Binds bacterial ribosomes to halt protein production, preventing bacterial replication.',
    administrationAdvice: 'Take once daily. Can be taken with or without food, but food helps prevent mild stomach upset. Complete full prescribed 3 or 5 day regimen.',
    sideEffects: {
      common: ['Mild stomach cramps', 'Nausea', 'Loose stools'],
      important: ['Temporary ringing in ears', 'Dizziness'],
      urgent: ['Irregular heart rhythm (palpitations)', 'Severe watery diarrhea with fever', 'Yellowing of eyes/skin'],
    },
    precautions: [
      'Take antacids containing aluminum or magnesium at least 2 hours apart.',
      'Complete the full 3-day or 5-day course even if feeling better.',
    ],
    storage: 'Store at room temperature in a dry place.',
    missedDoseAdvice: 'Take as soon as remembered on that day.',
  },
  cefixime: {
    genericName: 'Cefixime',
    brandAliases: ['zifi', 'taxim-o', 'mahacef', 'cefolac', 'suprax', 'omnicef'],
    activeIngredients: ['Cefixime'],
    category: '3rd Generation Cephalosporin Antibiotic',
    commonStrengths: ['100 mg', '200 mg', '400 mg', '50 mg/5ml', '100 mg/5ml'],
    dosageForms: ['Tablet', 'Dispersible Tablet', 'Dry Syrup'],
    commonUses: ['Urinary tract infections (UTI)', 'Typhoid fever / enteric infections', 'Bronchitis, otitis media (ear infections)'],
    howItWorksSimple: 'Kills bacteria by breaking down bacterial cell wall synthesis.',
    administrationAdvice: 'Take once or twice daily with food or water. Complete full course.',
    sideEffects: {
      common: ['Loose stools', 'Stomach upset', 'Nausea'],
      important: ['Mild skin itching', 'Headache'],
      urgent: ['Severe allergic reaction with hives or difficulty breathing', 'Severe watery diarrhea with fever'],
    },
    precautions: ['Inform doctor if allergic to cephalosporin or penicillin antibiotics.'],
    storage: 'Store below 25°C.',
    missedDoseAdvice: 'Take as soon as remembered, spacing remaining doses evenly.',
  },
  ciprofloxacin: {
    genericName: 'Ciprofloxacin',
    brandAliases: ['ciplox', 'cipro', 'cifran', 'ciproglen'],
    activeIngredients: ['Ciprofloxacin'],
    category: 'Fluoroquinolone Antibiotic',
    commonStrengths: ['250 mg', '500 mg', '750 mg', '0.3% Eye/Ear Drops'],
    dosageForms: ['Tablet', 'Eye/Ear Drops', 'IV Infusion'],
    commonUses: ['Severe urinary tract infections', 'Gastrointestinal bacterial infections / infectious diarrhea', 'Bone/joint infections'],
    howItWorksSimple: 'Inhibits bacterial DNA gyrase and topoisomerase IV, preventing bacterial DNA replication.',
    administrationAdvice: 'Take twice daily with a full glass of water. Avoid taking dairy products (milk, yogurt) or calcium supplements at the exact same time.',
    sideEffects: {
      common: ['Nausea', 'Mild diarrhea', 'Headache'],
      important: ['Dizziness', 'Increased sun sensitivity (sunburn easily)'],
      urgent: ['Tendon pain or swelling (Achilles tendonitis)', 'Nerve tingling in extremities', 'Severe palpitations'],
    },
    precautions: [
      'Drink plenty of fluids while taking ciprofloxacin to prevent crystal formation in kidneys.',
      'Avoid heavy athletic exertion while on treatment due to tendon vulnerability.',
    ],
    storage: 'Store at room temperature away from light.',
    missedDoseAdvice: 'Take as soon as remembered unless within 6 hours of next dose.',
  },
  metformin: {
    genericName: 'Metformin',
    brandAliases: ['glycomet', 'glucophage', 'glyciphage', 'riomet', 'janumet', 'galvus met', 'formet'],
    activeIngredients: ['Metformin'],
    category: 'Biguanide Antidiabetic Medication',
    commonStrengths: ['500 mg', '850 mg', '1000 mg', '500 mg SR', '1000 mg SR'],
    dosageForms: ['Tablet', 'Sustained Release (SR/ER) Tablet'],
    commonUses: ['Type 2 Diabetes Mellitus blood glucose control', 'PCOS insulin sensitivity management'],
    howItWorksSimple: 'Decreases glucose production in the liver, reduces glucose absorption in gut, and improves cell insulin sensitivity.',
    administrationAdvice: 'Take with or immediately after meals (breakfast and/or dinner) with water. Swallow SR tablets whole without crushing.',
    sideEffects: {
      common: ['Nausea, loose stools during first few weeks', 'Metallic taste in mouth', 'Bloating'],
      important: ['Vitamin B12 deficiency symptoms (finger/toe tingling, fatigue) with long-term use'],
      urgent: ['Lactic acidosis: severe unusual muscle cramps, heavy breathing, extreme weakness, severe cold feeling'],
    },
    precautions: [
      'Take with meals to avoid stomach upset.',
      'Inform imaging staff before receiving CT contrast scans.',
      'Avoid excessive alcohol consumption.',
    ],
    storage: 'Keep container tightly closed in dry location.',
    missedDoseAdvice: 'Take with next meal. Do not take double doses.',
  },
  glimepiride: {
    genericName: 'Glimepiride',
    brandAliases: ['amaryl', 'zoryl', 'glimy', 'gemer', 'glimestar'],
    activeIngredients: ['Glimepiride', 'Metformin (in Gemer / Glimestar-M)'],
    category: 'Sulfonylurea Antidiabetic Agent',
    commonStrengths: ['1 mg', '2 mg', '3 mg', '4 mg'],
    dosageForms: ['Tablet'],
    commonUses: ['Type 2 Diabetes glucose control'],
    howItWorksSimple: 'Stimulates the beta cells of the pancreas to release more natural insulin into the bloodstream.',
    administrationAdvice: 'Take once daily immediately before or with breakfast (or first main meal). Do not skip meals after taking.',
    sideEffects: {
      common: ['Low blood sugar (hypoglycemia symptoms: sweating, shakiness, hunger, dizziness)'],
      important: ['Weight gain', 'Mild nausea'],
      urgent: ['Severe hypoglycemia: confusion, fainting (treat immediately with glucose/juice)'],
    },
    precautions: ['Always carry fast-acting sugar (candy, glucose tablets) in case of sudden shakiness or sweating.'],
    storage: 'Store below 25°C in original package.',
    missedDoseAdvice: 'Take with your next meal if remembered, but never take double tablets.',
  },
  telmisartan: {
    genericName: 'Telmisartan',
    brandAliases: ['telma', 'telma-40', 'telma-h', 'telma-am', 'micardis', 'telmikem', 'telsartan'],
    activeIngredients: ['Telmisartan', 'Hydrochlorothiazide (in Telma-H)', 'Amlodipine (in Telma-AM)'],
    category: 'Angiotensin II Receptor Blocker (ARB / Blood Pressure)',
    commonStrengths: ['20 mg', '40 mg', '80 mg', '40 mg + 12.5 mg', '40 mg + 5 mg'],
    dosageForms: ['Tablet'],
    commonUses: ['Hypertension (High Blood Pressure)', 'Cardiovascular risk reduction in diabetic/cardiac patients'],
    howItWorksSimple: 'Blocks angiotensin II receptors, relaxing and dilating blood vessels to reduce arterial pressure.',
    administrationAdvice: 'Take once daily at the same time every day (morning or evening), with or without food.',
    sideEffects: {
      common: ['Dizziness when standing up', 'Fatigue', 'Sinus congestion'],
      important: ['Elevated blood potassium levels'],
      urgent: ['Severe facial or throat swelling (angioedema)', 'Unexplained fainting or severe hypotension'],
    },
    precautions: [
      'Do not stop taking abruptly even if you feel completely normal.',
      'Avoid salt substitutes containing potassium without consulting doctor.',
      'Contraindicated in pregnancy.',
    ],
    storage: 'Store in moisture-proof blister pack below 30°C.',
    missedDoseAdvice: 'Take as soon as remembered that day. Resume normal schedule next morning.',
  },
  amlodipine: {
    genericName: 'Amlodipine',
    brandAliases: ['amlong', 'amlovas', 'norvasc', 'stamlo', 'amlotas'],
    activeIngredients: ['Amlodipine'],
    category: 'Calcium Channel Blocker (CCB / Blood Pressure)',
    commonStrengths: ['2.5 mg', '5 mg', '10 mg'],
    dosageForms: ['Tablet'],
    commonUses: ['High blood pressure', 'Angina (coronary chest pain)'],
    howItWorksSimple: 'Relaxes smooth muscles in arterial walls to lower blood pressure and improve blood flow to the heart.',
    administrationAdvice: 'Take once daily at the same time each day with water.',
    sideEffects: {
      common: ['Swelling in ankles/feet (peripheral edema)', 'Dizziness', 'Warm flushing'],
      important: ['Fatigue', 'Palpitations'],
      urgent: ['Worsening chest pain upon starting treatment', 'Severe allergic reaction'],
    },
    precautions: ['Stand up gradually from seated or lying position.', 'Do not stop abruptly.'],
    storage: 'Store in dry place protected from light.',
    missedDoseAdvice: 'Take as soon as remembered if within 12 hours.',
  },
  atorvastatin: {
    genericName: 'Atorvastatin',
    brandAliases: ['atorva', 'lipitor', 'storvas', 'lipvas', 'tonact', 'atorlip'],
    activeIngredients: ['Atorvastatin'],
    category: 'HMG-CoA Reductase Inhibitor (Statin / Cholesterol)',
    commonStrengths: ['10 mg', '20 mg', '40 mg', '80 mg'],
    dosageForms: ['Tablet'],
    commonUses: ['Lowering LDL cholesterol and triglycerides', 'Heart attack and stroke prevention'],
    howItWorksSimple: 'Blocks cholesterol synthesis in the liver, clearing plaque-forming lipids from the bloodstream.',
    administrationAdvice: 'Take once daily, usually in the evening or at bedtime, with or without food.',
    sideEffects: {
      common: ['Mild muscle or joint aches', 'Mild digestive upset'],
      important: ['Persistent unexplained muscle pain or tenderness in thighs/shoulders'],
      urgent: ['Rhabdomyolysis: dark brown tea-colored urine with intense muscle soreness and weakness'],
    },
    precautions: ['Avoid large amounts of grapefruit juice.', 'Notify doctor of any unexplained muscle aches.'],
    storage: 'Store below 25°C in a dry place.',
    missedDoseAdvice: 'Take as soon as remembered within 12 hours.',
  },
  rosuvastatin: {
    genericName: 'Rosuvastatin',
    brandAliases: ['rozavel', 'crestor', 'rosuvas', 'razel', 'turbovas'],
    activeIngredients: ['Rosuvastatin'],
    category: 'Statin / Cholesterol Reducer',
    commonStrengths: ['5 mg', '10 mg', '20 mg', '40 mg'],
    dosageForms: ['Tablet'],
    commonUses: ['High cholesterol', 'Atherosclerosis prevention'],
    howItWorksSimple: 'Potent statin that inhibits hepatic cholesterol formation.',
    administrationAdvice: 'Take once daily at any time of day, with or without food.',
    sideEffects: {
      common: ['Headache', 'Muscle aches', 'Stomach pain'],
      important: ['Persistent muscle tenderness'],
      urgent: ['Tea-colored urine with extreme muscle weakness'],
    },
    precautions: ['Avoid during pregnancy.'],
    storage: 'Store at room temperature.',
    missedDoseAdvice: 'Take as soon as remembered within 12 hours.',
  },
  levocetirizine: {
    genericName: 'Levocetirizine & Montelukast',
    brandAliases: ['levocet', 'montair-lc', 'monticope', 'xyzal', 'telekast-l', 'levocet-m', 'lecope', '1-al'],
    activeIngredients: ['Levocetirizine', 'Montelukast (in Montair-LC / Levocet-M)'],
    category: 'Antihistamine & Leukotriene Receptor Antagonist',
    commonStrengths: ['5 mg', '5 mg + 10 mg', '2.5 mg/5ml'],
    dosageForms: ['Tablet', 'Syrup', 'Dispersible Tablet'],
    commonUses: ['Allergic rhinitis, sneezing, runny nose, watery eyes', 'Allergic asthma and chronic urticaria (hives)'],
    howItWorksSimple: 'Levocetirizine blocks histamine receptors to stop itching and runny nose; Montelukast blocks leukotrienes to ease airway breathing.',
    administrationAdvice: 'Take once daily in the evening or at bedtime with water.',
    sideEffects: {
      common: ['Mild drowsiness', 'Dry mouth', 'Fatigue'],
      important: ['Headache', 'Vivid dreams'],
      urgent: ['Severe mood changes / anxiety', 'Severe allergic hives with breathing difficulty'],
    },
    precautions: ['May cause mild drowsiness; avoid driving or operating heavy machinery until you know how it affects you.'],
    storage: 'Store in moisture-proof blister below 25°C.',
    missedDoseAdvice: 'Take at night as soon as remembered.',
  },
  cetirizine: {
    genericName: 'Cetirizine',
    brandAliases: ['cetzine', 'zyrtec', 'alerdic', 'okacet', 'cetz'],
    activeIngredients: ['Cetirizine'],
    category: 'Second-Generation Antihistamine',
    commonStrengths: ['5 mg', '10 mg', '5 mg/5ml'],
    dosageForms: ['Tablet', 'Syrup'],
    commonUses: ['Allergies, hay fever, skin rash, insect bites'],
    howItWorksSimple: 'Blocks peripheral H1 histamine receptors to halt allergic symptoms.',
    administrationAdvice: 'Take once daily, preferably at night.',
    sideEffects: {
      common: ['Mild drowsiness', 'Dry mouth'],
      important: ['Tiredness'],
      urgent: ['Facial swelling or breathing difficulty'],
    },
    precautions: ['Avoid combining with alcohol.'],
    storage: 'Store at room temperature.',
    missedDoseAdvice: 'Take once daily as needed.',
  },
  dextromethorphan: {
    genericName: 'Dextromethorphan & Chlorpheniramine (Cough Syrup)',
    brandAliases: ['ascoril-d', 'benadryl-dr', 'chericof', 'tossex', 'grilinctus', 'koflet'],
    activeIngredients: ['Dextromethorphan Hydrobromide', 'Chlorpheniramine Maleate', 'Phenylephrine'],
    category: 'Antitussive Cough Suppressant Complex',
    commonStrengths: ['10 mg/5ml', '100 ml bottle'],
    dosageForms: ['Syrup', 'Linctus'],
    commonUses: ['Dry, non-productive irritating cough', 'Cold and throat tickle relief'],
    howItWorksSimple: 'Acts on the cough center in the brain medulla to suppress the cough reflex.',
    administrationAdvice: 'Measure with measuring cup (e.g. 5ml to 10ml) 2 to 3 times daily after food.',
    sideEffects: {
      common: ['Mild sleepiness', 'Dizziness', 'Nausea'],
      important: ['Dry mouth', 'Constipation'],
      urgent: ['Extreme drowsiness / slow breathing in overdose'],
    },
    precautions: ['Do not use for productive wet cough with heavy mucus without doctor advice.', 'Keep out of reach of children.'],
    storage: 'Keep bottle tightly closed at room temperature.',
    missedDoseAdvice: 'Take when cough symptoms occur, maintaining 6 to 8 hours between doses.',
  },
  calcium: {
    genericName: 'Calcium Carbonate & Vitamin D3',
    brandAliases: ['shelcal', 'shelcal-500', 'calcirol', 'gemcal', 'cipcal', 'ostocalcium'],
    activeIngredients: ['Elemental Calcium', 'Vitamin D3 (Cholecalciferol)'],
    category: 'Nutritional Mineral & Vitamin Supplement',
    commonStrengths: ['500 mg + 250 IU', '500 mg + 400 IU', '60,000 IU (D3 weekly)'],
    dosageForms: ['Tablet', 'Chewable Tablet', 'Sachet'],
    commonUses: ['Osteoporosis prevention and bone strength', 'Calcium and Vitamin D deficiency', 'Post-fracture healing'],
    howItWorksSimple: 'Replenishes elemental calcium for bone mineral density while Vitamin D3 facilitates intestinal calcium absorption.',
    administrationAdvice: 'Take after lunch or dinner with plenty of water for optimal absorption.',
    sideEffects: {
      common: ['Mild constipation', 'Gas / bloating'],
      important: ['Nausea'],
      urgent: ['Signs of hypercalcemia: extreme thirst, frequent urination, confusion'],
    },
    precautions: ['Drink plenty of water throughout the day to prevent kidney stone formation.', 'Separate from iron supplements by at least 2 hours.'],
    storage: 'Store in cool and dry place away from direct sunlight.',
    missedDoseAdvice: 'Take after your next meal.',
  },
  bcomplex: {
    genericName: 'Vitamin B-Complex & Zinc / Neurobion',
    brandAliases: ['becosules', 'becosules-z', 'neurobion forte', 'polybion', 'optineuron', 'supradyn'],
    activeIngredients: ['B1, B2, B3, B6, B12 (Cyanocobalamin)', 'Zinc', 'Folic Acid'],
    category: 'Multivitamin & Nerve Health Complex',
    commonStrengths: ['Standard Therapeutic Capsule', 'Injection'],
    dosageForms: ['Capsule', 'Tablet', 'Injection'],
    commonUses: ['Mouth ulcers and glossitis', 'Peripheral nerve tingling / neuropathy', 'General fatigue and post-illness recovery'],
    howItWorksSimple: 'Essential coenzymes that support nerve myelin sheath repair, red blood cell formation, and cellular energy metabolism.',
    administrationAdvice: 'Take 1 capsule daily after breakfast or lunch with water.',
    sideEffects: {
      common: ['Bright yellow urine (harmless due to riboflavin excretion)', 'Mild stomach warmth'],
      important: ['Mild nausea'],
      urgent: ['Severe allergic reaction'],
    },
    precautions: ['Urine turning bright yellow is completely normal and harmless.'],
    storage: 'Store below 25°C in dry conditions.',
    missedDoseAdvice: 'Take after the next meal.',
  },
  ondansetron: {
    genericName: 'Ondansetron',
    brandAliases: ['emeset', 'emeset-md', 'zofran', 'vomikind', 'onesta'],
    activeIngredients: ['Ondansetron'],
    category: '5-HT3 Receptor Antagonist (Antiemetic / Anti-Nausea)',
    commonStrengths: ['4 mg', '8 mg', '2 mg/5ml', '4 mg MD (Mouth Dissolving)'],
    dosageForms: ['Tablet', 'Mouth Dissolving Tablet (MD)', 'Syrup', 'Injection'],
    commonUses: ['Nausea and vomiting prevention', 'Gastroenteritis nausea', 'Post-operative or chemotherapy nausea'],
    howItWorksSimple: 'Blocks serotonin 5-HT3 receptors in the vagal nerve terminals and brain chemoreceptor trigger zone to stop nausea.',
    administrationAdvice: 'Take 30 minutes before meals or chemotherapy. For MD tablets, place on tongue to dissolve without water.',
    sideEffects: {
      common: ['Headache', 'Constipation', 'Flushing'],
      important: ['Drowsiness'],
      urgent: ['Severe dizziness or irregular heartbeat (QT prolongation)'],
    },
    precautions: ['Follow exact frequency prescribed.'],
    storage: 'Store at room temperature.',
    missedDoseAdvice: 'Take as needed for nausea.',
  },
  doxycycline: {
    genericName: 'Doxycycline',
    brandAliases: ['dox-100', 'doxy-1', 'vibramycin', 'microdox', 'doxylin'],
    activeIngredients: ['Doxycycline Hyclate / Monohydrate'],
    category: 'Tetracycline Antibiotic',
    commonStrengths: ['100 mg', '50 mg'],
    dosageForms: ['Capsule', 'Tablet'],
    commonUses: ['Respiratory infections', 'Acne and skin infections', 'Tick-borne infections, malaria prophylaxis'],
    howItWorksSimple: 'Inhibits bacterial protein synthesis by binding to the 30S ribosomal subunit.',
    administrationAdvice: 'Take with a full glass of water while sitting or standing upright. Do not lie down for at least 30 minutes after taking to prevent esophageal irritation.',
    sideEffects: {
      common: ['Nausea', 'Sun sensitivity (sunburns easily)', 'Stomach ache'],
      important: ['Vaginal yeast infection', 'Esophageal irritation'],
      urgent: ['Severe headache with blurred vision', 'Severe allergic reaction'],
    },
    precautions: ['Avoid calcium, iron, or antacid supplements within 2 hours of dose.', 'Contraindicated in pregnancy and young children.'],
    storage: 'Store below 25°C away from direct sunlight.',
    missedDoseAdvice: 'Take as soon as remembered with full glass of water.',
  },
  metronidazole: {
    genericName: 'Metronidazole',
    brandAliases: ['flagyl', 'metrogyl', 'metrogyl-400', 'metron', 'aldazole'],
    activeIngredients: ['Metronidazole'],
    category: 'Nitroimidazole Antimicrobial / Antiprotozoal',
    commonStrengths: ['200 mg', '400 mg', '500 mg', '200 mg/5ml'],
    dosageForms: ['Tablet', 'Suspension', 'IV Infusion', 'Gel'],
    commonUses: ['Amoebiasis, giardiasis, dental bacterial infections', 'Anaerobic bacterial infections', 'Gastrointestinal infections'],
    howItWorksSimple: 'Damages bacterial and protozoal DNA, halting cell replication.',
    administrationAdvice: 'Take during or immediately after meals with a full glass of water.',
    sideEffects: {
      common: ['Metallic taste in mouth', 'Dark brown urine (harmless)', 'Nausea'],
      important: ['Loss of appetite', 'Headache'],
      urgent: ['Severe peripheral numbness/tingling (neuropathy)', 'Seizures or confusion'],
    },
    precautions: ['STRICTLY AVOID ALCOHOL during treatment and for 48 hours after stopping (causes severe nausea, vomiting, palpitations).'],
    storage: 'Store at room temperature in a dry place.',
    missedDoseAdvice: 'Take as soon as remembered with food.',
  },
  levofloxacin: {
    genericName: 'Levofloxacin',
    brandAliases: ['levomac', 'levaquin', 'l-cin', 'glevo'],
    activeIngredients: ['Levofloxacin'],
    category: 'Fluoroquinolone Antibiotic',
    commonStrengths: ['250 mg', '500 mg', '750 mg'],
    dosageForms: ['Tablet', 'IV Infusion', 'Eye Drops'],
    commonUses: ['Pneumonia, acute sinusitis', 'Complicated urinary tract infections', 'Skin infections'],
    howItWorksSimple: 'Inhibits bacterial DNA gyrase to kill susceptible bacteria.',
    administrationAdvice: 'Take once daily with plenty of water. Separate from antacids/iron by 2 hours.',
    sideEffects: {
      common: ['Nausea', 'Headache', 'Dizziness'],
      important: ['Sun sensitivity', 'Sleep disturbances'],
      urgent: ['Tendon pain (Achilles tendonitis)', 'Nerve pain or tingling'],
    },
    precautions: ['Stay well hydrated.', 'Avoid strenuous exercise during therapy.'],
    storage: 'Store in dry place below 30°C.',
    missedDoseAdvice: 'Take as soon as remembered if more than 8 hours before next dose.',
  },
  prednisolone: {
    genericName: 'Prednisolone / Methylprednisolone',
    brandAliases: ['wysolone', 'omnacortil', 'medrol', 'predone', 'solu-medrol'],
    activeIngredients: ['Prednisolone / Methylprednisolone'],
    category: 'Corticosteroid (Anti-Inflammatory & Immunosuppressant)',
    commonStrengths: ['5 mg', '10 mg', '20 mg', '40 mg', '4 mg', '8 mg', '16 mg'],
    dosageForms: ['Tablet', 'Dispersible Tablet', 'Syrup', 'Injection'],
    commonUses: ['Severe allergic reactions, acute asthma flare-ups', 'Autoimmune and inflammatory disorders', 'Skin eczema/dermatitis'],
    howItWorksSimple: 'Suppresses inflammation and immune system overactivity.',
    administrationAdvice: 'Take strictly in the morning after breakfast to mimic the body natural cortisol rhythm. Do not stop abruptly if taken for more than 2 weeks (requires tapering).',
    sideEffects: {
      common: ['Increased appetite', 'Mild fluid retention', 'Insomnia if taken late'],
      important: ['Elevated blood glucose', 'Mood changes', 'Stomach irritation'],
      urgent: ['Severe stomach pain/bleeding', 'Signs of infection (fever, chills)'],
    },
    precautions: ['Always take with food.', 'Never stop suddenly without doctor tapering schedule.'],
    storage: 'Store below 25°C in dry container.',
    missedDoseAdvice: 'Take with food on the same morning if remembered.',
  },
  fexofenadine: {
    genericName: 'Fexofenadine',
    brandAliases: ['allegra', 'fexova', 'fexy', 'allegra-120', 'allegra-180'],
    activeIngredients: ['Fexofenadine Hydrochloride'],
    category: 'Non-Drowsy Second-Generation Antihistamine',
    commonStrengths: ['30 mg', '60 mg', '120 mg', '180 mg', '30 mg/5ml'],
    dosageForms: ['Tablet', 'Suspension'],
    commonUses: ['Seasonal allergies, hay fever, sneezing, itchy watery eyes', 'Chronic skin hives (urticaria)'],
    howItWorksSimple: 'Selectively blocks peripheral H1 histamine receptors without entering the brain, avoiding drowsiness.',
    administrationAdvice: 'Take once daily with plain water. Avoid fruit juices (apple, orange, grapefruit) 2 hours before/after taking as they reduce absorption.',
    sideEffects: {
      common: ['Headache', 'Drowsiness (rare)', 'Dry mouth'],
      important: ['Mild nausea', 'Dizziness'],
      urgent: ['Severe allergic swelling of throat or face'],
    },
    precautions: ['Take with plain water only; avoid fruit juices.'],
    storage: 'Store at room temperature away from excessive moisture.',
    missedDoseAdvice: 'Take as soon as remembered once daily.',
  },
  tramadol: {
    genericName: 'Tramadol & Paracetamol',
    brandAliases: ['ultracet', 'tramazac', 'calpol-t', 'tramasure', 'domadol'],
    activeIngredients: ['Tramadol Hydrochloride', 'Paracetamol'],
    category: 'Central Analgesic & Opioid-Receptor Agonist',
    commonStrengths: ['37.5 mg + 325 mg', '50 mg', '100 mg SR'],
    dosageForms: ['Tablet', 'Capsule', 'Injection'],
    commonUses: ['Moderate to severe acute pain (post-surgical, trauma, severe dental pain)'],
    howItWorksSimple: 'Binds mu-opioid receptors and inhibits serotonin and norepinephrine reuptake to dampen pain signals.',
    administrationAdvice: 'Take as prescribed with food and water. Do not exceed prescribed frequency.',
    sideEffects: {
      common: ['Dizziness', 'Drowsiness', 'Nausea / constipation'],
      important: ['Dry mouth', 'Sweating'],
      urgent: ['Severe breathing slowness (respiratory depression)', 'Extreme dizziness or fainting'],
    },
    precautions: ['Causes drowsiness; do not drive.', 'Avoid alcohol.', 'Do not combine with other paracetamol products.'],
    storage: 'Store securely out of reach of children.',
    missedDoseAdvice: 'Take when needed for pain, observing minimum 6-hour spacing.',
  },
  mefenamic_acid: {
    genericName: 'Mefenamic Acid & Dicyclomine',
    brandAliases: ['meftal', 'meftal-spas', 'meftal-forte', 'dysmen'],
    activeIngredients: ['Mefenamic Acid', 'Dicyclomine Hydrochloride (in Meftal-Spas)'],
    category: 'Antispasmodic & NSAID Analgesic',
    commonStrengths: ['250 mg', '500 mg', '250 mg + 10 mg', '500 mg + 20 mg'],
    dosageForms: ['Tablet', 'Syrup'],
    commonUses: ['Menstrual cramps (dysmenorrhea)', 'Spasmodic abdominal pain, intestinal colic'],
    howItWorksSimple: 'Mefenamic acid reduces pain prostaglandins while Dicyclomine relaxes smooth muscle spasms in the gut and uterus.',
    administrationAdvice: 'Take with or after food with water. Use only as needed for cramps.',
    sideEffects: {
      common: ['Dry mouth', 'Mild dizziness', 'Heartburn'],
      important: ['Blurred vision', 'Nausea'],
      urgent: ['Severe gastrointestinal pain or bleeding'],
    },
    precautions: ['Take strictly with food.', 'Do not combine with other NSAID painkillers.'],
    storage: 'Store below 30°C.',
    missedDoseAdvice: 'Take when pain/spasm occurs with food.',
  },
  drotaverine: {
    genericName: 'Drotaverine',
    brandAliases: ['drotin', 'drotin-m', 'drotikind', 'drotin-plus'],
    activeIngredients: ['Drotaverine Hydrochloride', 'Mefenamic Acid (in Drotin-M)'],
    category: 'Smooth Muscle Antispasmodic',
    commonStrengths: ['40 mg', '80 mg', '80 mg + 250 mg'],
    dosageForms: ['Tablet', 'Syrup', 'Injection'],
    commonUses: ['Abdominal cramping, renal colic, biliary colic, menstrual pain'],
    howItWorksSimple: 'Inhibits phosphodiesterase-4 (PDE4) enzymes to relieve smooth muscle spasms in abdominal organs.',
    administrationAdvice: 'Take with or without meals with water when spasms occur.',
    sideEffects: {
      common: ['Dizziness', 'Headache', 'Nausea'],
      important: ['Palpitations', 'Dry mouth'],
      urgent: ['Allergic skin rash or low blood pressure'],
    },
    precautions: ['Use with caution in patients with low blood pressure or liver conditions.'],
    storage: 'Store in cool, dry conditions.',
    missedDoseAdvice: 'Take when cramps occur.',
  },
  domperidone: {
    genericName: 'Domperidone',
    brandAliases: ['domstal', 'motilium', 'domi', 'vomistop'],
    activeIngredients: ['Domperidone'],
    category: 'Dopamine D2 Antagonist (Prokinetic & Antiemetic)',
    commonStrengths: ['10 mg', '10 mg DT', '1 mg/ml'],
    dosageForms: ['Tablet', 'Dispersible Tablet', 'Syrup'],
    commonUses: ['Nausea, vomiting, delayed gastric emptying, bloating, fullness after meals'],
    howItWorksSimple: 'Blocks dopamine receptors in the upper gut and chemoreceptor trigger zone to facilitate normal stomach emptying.',
    administrationAdvice: 'Take 15–30 minutes before meals.',
    sideEffects: {
      common: ['Dry mouth', 'Headache', 'Mild diarrhea'],
      important: ['Breast tenderness or milk secretion (hyperprolactinemia) with prolonged use'],
      urgent: ['Irregular heart rhythm (palpitations)'],
    },
    precautions: ['Take before meals.', 'Do not exceed 30 mg per day in adults.'],
    storage: 'Store below 25°C.',
    missedDoseAdvice: 'Take before your next meal.',
  },
  clopidogrel: {
    genericName: 'Clopidogrel & Aspirin',
    brandAliases: ['plavix', 'clopilet', 'deplatt', 'clopivas', 'clopilet-a', 'deplatt-a'],
    activeIngredients: ['Clopidogrel', 'Aspirin (in Clopilet-A / Deplatt-A)'],
    category: 'Antiplatelet Agent (Blood Thinner)',
    commonStrengths: ['75 mg', '75 mg + 75 mg', '75 mg + 150 mg'],
    dosageForms: ['Tablet'],
    commonUses: ['Prevention of blood clots after heart stents, heart attack, or ischemic stroke'],
    howItWorksSimple: 'Irreversibly inhibits ADP P2Y12 receptors on platelets to prevent dangerous clot aggregation in arteries.',
    administrationAdvice: 'Take once daily at the same time every day with food and water. Do not stop without cardiologist permission.',
    sideEffects: {
      common: ['Easy bruising', 'Minor bleeding from cuts that takes longer to stop', 'Nosebleeds'],
      important: ['Indigestion', 'Stomach irritation'],
      urgent: ['Black tarry stools, vomiting blood, red/pink urine, sudden severe headache'],
    },
    precautions: ['Never discontinue without consulting your cardiologist.', 'Notify dentists or surgeons before any procedures.'],
    storage: 'Store below 25°C protected from moisture.',
    missedDoseAdvice: 'Take as soon as remembered on that day. Do not double doses.',
  },
  aspirin: {
    genericName: 'Aspirin (Low-Dose / Enteric Coated)',
    brandAliases: ['ecosprin', 'ecosprin-75', 'ecosprin-150', 'disprin', 'aspin'],
    activeIngredients: ['Aspirin (Acetylsalicylic Acid)'],
    category: 'Antiplatelet / Cardioprotective Agent',
    commonStrengths: ['75 mg', '150 mg', '325 mg', '500 mg'],
    dosageForms: ['Enteric Coated Tablet', 'Effervescent Tablet'],
    commonUses: ['Cardiovascular and stroke prevention', 'Post-angioplasty stent maintenance'],
    howItWorksSimple: 'Inhibits thromboxane A2 synthesis in platelets to stop blood clot formation.',
    administrationAdvice: 'Take once daily after meals with a full glass of water. Swallow enteric-coated tablets whole.',
    sideEffects: {
      common: ['Mild stomach irritation', 'Easy bruising'],
      important: ['Heartburn'],
      urgent: ['Gastrointestinal bleeding (dark stools), vomiting blood, ringing in ears (tinnitus)'],
    },
    precautions: ['Always take after food.', 'Avoid combining with other NSAID painkillers.'],
    storage: 'Store in tightly closed container in dry place.',
    missedDoseAdvice: 'Take after your next meal on the same day.',
  },
  levothyroxine: {
    genericName: 'Levothyroxine Sodium',
    brandAliases: ['thyronorm', 'eltroxin', 'synthroid', 'thyrox'],
    activeIngredients: ['Levothyroxine Sodium (T4)'],
    category: 'Thyroid Hormone Replacement',
    commonStrengths: ['25 mcg', '50 mcg', '75 mcg', '88 mcg', '100 mcg', '112 mcg', '125 mcg', '150 mcg'],
    dosageForms: ['Tablet'],
    commonUses: ['Hypothyroidism (Underactive thyroid gland)', 'Goiter management'],
    howItWorksSimple: 'Provides synthetic thyroxine (T4) that the body converts into active T3 to maintain normal metabolism.',
    administrationAdvice: 'Take once daily strictly in the morning on an empty stomach with plain water, at least 30 to 60 minutes before breakfast, tea, or coffee.',
    sideEffects: {
      common: ['Weight changes (normalization)', 'Mild hair shedding during first few weeks'],
      important: ['Sweating', 'Shakiness if dose is too high'],
      urgent: ['Chest pain, rapid or pounding heart rate (palpitations), severe insomnia'],
    },
    precautions: [
      'Take strictly on an empty stomach with plain water.',
      'Separate calcium, iron supplements, and antacids by at least 4 hours.',
      'Have periodic TSH blood tests as advised by doctor.',
    ],
    storage: 'Store below 25°C in original container protected from light and humidity.',
    missedDoseAdvice: 'Take as soon as remembered on an empty stomach, or resume next morning.',
  },
  salbutamol: {
    genericName: 'Salbutamol / Albuterol & Budesonide',
    brandAliases: ['asthalin', 'ventolin', 'foracort', 'budecort', 'seroflo', 'aerocort'],
    activeIngredients: ['Salbutamol / Formoterol', 'Budesonide (in Foracort / Budecort)'],
    category: 'Bronchodilator & Inhaled Corticosteroid',
    commonStrengths: ['100 mcg Inhaler', '200 mcg Inhaler', '2 mg Tablet', '4 mg Tablet', 'Nebulizer Respules (0.5mg/2ml)'],
    dosageForms: ['Metered Dose Inhaler (MDI)', 'Rotacaps / Dry Powder Inhaler', 'Respules', 'Syrup', 'Tablet'],
    commonUses: ['Asthma flare-ups, wheezing, shortness of breath', 'Chronic Obstructive Pulmonary Disease (COPD)'],
    howItWorksSimple: 'Relaxes constricted bronchial smooth muscles in airways to open breathing passages quickly; Budesonide reduces airway swelling.',
    administrationAdvice: 'Inhale through mouth using spacer or proper inhaler technique. Always rinse mouth and gargle with water after using steroid inhalers (Budecort/Foracort) to prevent hoarseness and oral thrush.',
    sideEffects: {
      common: ['Mild hand tremor', 'Fast heartbeat for 10–15 minutes after inhalation', 'Throat irritation'],
      important: ['Hoarse voice', 'Oral white patches (rinse mouth after use to prevent)'],
      urgent: ['Severe paradox bronchospasm (worsening wheezing immediately after puff)'],
    },
    precautions: [
      'Always rinse mouth and spit water out after using steroid inhalers.',
      'Keep rescue inhaler readily accessible.',
    ],
    storage: 'Store inhaler below 30°C away from direct heat and freezing.',
    missedDoseAdvice: 'Take maintenance puffs as scheduled.',
  },
  moxifloxacin_eye: {
    genericName: 'Moxifloxacin & Lubricant Eye Drops',
    brandAliases: ['moxicip', 'vigamox', 'moxif', 'refresh tears', 'tears naturale', 'systane', 'moxicip-kt'],
    activeIngredients: ['Moxifloxacin 0.5%', 'Carboxymethylcellulose 0.5% (in Refresh Tears)'],
    category: 'Ophthalmic Antibacterial & Ocular Lubricant',
    commonStrengths: ['0.5% w/v Drops', '0.5% CMC Drops'],
    dosageForms: ['Eye Drops', 'Eye Ointment'],
    commonUses: ['Bacterial conjunctivitis (pink eye)', 'Post-cataract / eye surgery prophylaxis', 'Dry eye syndrome'],
    howItWorksSimple: 'Moxifloxacin kills ocular bacteria by inhibiting DNA gyrase; lubricant drops stabilize the tear film to soothe dryness.',
    administrationAdvice: 'Wash hands thoroughly. Tilt head back, pull down lower eyelid, and instill 1 drop. Do not touch dropper tip to eye or fingers. Keep eye closed for 1 minute.',
    sideEffects: {
      common: ['Temporary mild stinging or blurring for 1–2 minutes after instillation'],
      important: ['Eye redness', 'Dryness'],
      urgent: ['Severe eye pain, sudden vision changes, severe swelling of eyelid'],
    },
    precautions: [
      'Discard bottle 30 days after opening.',
      'Remove contact lenses before applying antibiotic eye drops.',
      'Wait 5 minutes between different eye drop medications.',
    ],
    storage: 'Store in cool place below 25°C. Do not freeze.',
    missedDoseAdvice: 'Instill 1 drop as soon as remembered.',
  },
};

export const KNOWN_INTERACTIONS: DrugInteraction[] = [
  {
    id: 'int_warf_aspirin',
    medicineA: 'Warfarin',
    medicineB: 'Aspirin',
    status: 'significant_interaction',
    severity: 'major',
    description: 'Combining Warfarin with Aspirin (or NSAIDs) significantly increases the risk of severe gastrointestinal and internal bleeding.',
    mechanism: 'Both agents inhibit blood clotting mechanisms concurrently (anticoagulant + antiplatelet effect).',
    recommendation: 'Do not combine without explicit cardiologist/hematologist supervision and frequent INR monitoring.',
  },
  {
    id: 'int_warf_nsaid',
    medicineA: 'Warfarin',
    medicineB: 'Ibuprofen / Diclofenac / Aceclofenac',
    status: 'significant_interaction',
    severity: 'major',
    description: 'NSAIDs irritate the stomach lining and inhibit platelet aggregation, dramatically raising bleeding risk in patients taking Warfarin.',
    mechanism: 'NSAID-induced gastrointestinal mucosal damage plus systemic anticoagulation.',
    recommendation: 'Consult your doctor or pharmacist for a safer analgesic alternative (such as monitored paracetamol).',
  },
  {
    id: 'int_ace_potassium',
    medicineA: 'Ramipril / Enalapril / Telmisartan',
    medicineB: 'Spironolactone / Potassium Supplements',
    status: 'potential_interaction',
    severity: 'moderate',
    description: 'Combining ACE inhibitors or ARBs with potassium-sparing diuretics or potassium supplements can cause dangerously high blood potassium levels (hyperkalemia).',
    mechanism: 'Both reduce renal potassium excretion.',
    recommendation: 'Requires periodic blood serum potassium and creatinine monitoring by your healthcare provider.',
  },
  {
    id: 'int_clopidogrel_omeprazole',
    medicineA: 'Clopidogrel',
    medicineB: 'Omeprazole',
    status: 'potential_interaction',
    severity: 'moderate',
    description: 'Omeprazole may inhibit the liver enzyme CYP2C19 required to activate Clopidogrel, potentially reducing its blood-thinning effectiveness.',
    mechanism: 'CYP2C19 competitive inhibition in hepatic metabolism.',
    recommendation: 'Discuss switching to an alternative acid reducer (such as Pantoprazole or an H2 blocker) with your doctor.',
  },
  {
    id: 'int_statin_grapefruit',
    medicineA: 'Atorvastatin / Simvastatin',
    medicineB: 'Grapefruit Juice / Erythromycin / Clarithromycin',
    status: 'potential_interaction',
    severity: 'moderate',
    description: 'Macrolides or grapefruit products inhibit CYP3A4, causing statin concentration to spike and raising muscle toxicity risk.',
    mechanism: 'Inhibition of CYP3A4 hepatic clearance.',
    recommendation: 'Avoid consuming grapefruit products while on Atorvastatin or Simvastatin.',
  },
  {
    id: 'int_metformin_contrast',
    medicineA: 'Metformin',
    medicineB: 'Iodinated Radiocontrast Agents',
    status: 'potential_interaction',
    severity: 'moderate',
    description: 'Intravenous contrast dyes used in CT scans can temporarily impair kidney function, leading to potential Metformin accumulation and lactic acidosis.',
    mechanism: 'Contrast-induced nephropathy leading to reduced renal clearance of Metformin.',
    recommendation: 'Notify imaging staff and doctor; Metformin is usually paused 48 hours prior and post-procedure.',
  },
  {
    id: 'int_cipro_calcium',
    medicineA: 'Ciprofloxacin / Levofloxacin',
    medicineB: 'Calcium Supplements / Iron / Antacids',
    status: 'potential_interaction',
    severity: 'moderate',
    description: 'Divalent and trivalent cations (calcium, iron, aluminum, magnesium) bind to fluoroquinolones in the gut, drastically reducing antibiotic absorption.',
    mechanism: 'Chelation in gastrointestinal tract.',
    recommendation: 'Separate intake of calcium/antacids and ciprofloxacin by at least 2 hours.',
  },
  {
    id: 'int_nsaid_nsaid',
    medicineA: 'Ibuprofen / Aceclofenac / Diclofenac',
    medicineB: 'Mefenamic Acid / Naproxen / Ketorolac',
    status: 'significant_interaction',
    severity: 'major',
    description: 'Taking multiple different NSAID painkillers together does not improve pain relief but multiplies the risk of severe gastric ulcers and kidney strain.',
    mechanism: 'Cumulative COX-1 inhibition and gastrointestinal mucosal injury.',
    recommendation: 'Use only one single prescribed NSAID at a time.',
  },
];

export const DUPLICATE_INGREDIENTS_MAP: { ingredient: string; aliases: string[]; explanation: string }[] = [
  {
    ingredient: 'Paracetamol (Acetaminophen)',
    aliases: ['dolo', 'crocin', 'calpol', 'panadol', 'tylenol', 'pacimol', 'combiflam', 'ultracet', 'paracetamol', 'acetaminophen', 'zerodol-p', 'hifenac-p'],
    explanation: 'Multiple medications in your prescription contain Paracetamol. Combining them could lead to an accidental daily overdose exceeding 4,000 mg and cause liver strain.',
  },
  {
    ingredient: 'Ibuprofen',
    aliases: ['advil', 'motrin', 'brufen', 'nurofen', 'combiflam', 'ibuprofen', 'ibugesic'],
    explanation: 'Multiple medications contain Ibuprofen. Taking more than one NSAID increases the risk of severe stomach ulcers and kidney strain.',
  },
  {
    ingredient: 'Aspirin (Acetylsalicylic Acid)',
    aliases: ['ecosprin', 'disprin', 'aspirin', 'bayer aspirin', 'asaphen', 'sprin'],
    explanation: 'Multiple medicines contain Aspirin, compounding antiplatelet effects and bleeding risks.',
  },
  {
    ingredient: 'Proton Pump Inhibitors (Acid Reducers)',
    aliases: ['pantoprazole', 'omeprazole', 'rabeprazole', 'esomeprazole', 'pantocid', 'pan', 'pan-d', 'omez', 'razo', 'veloz', 'nexium', 'protonix'],
    explanation: 'Two different acid-suppression medications are prescribed simultaneously. Confirm whether one was intended to replace the other.',
  },
  {
    ingredient: 'Aceclofenac / Diclofenac',
    aliases: ['zerodol', 'hifenac', 'voveran', 'voltaren', 'dynapar', 'aceclo'],
    explanation: 'Multiple potent NSAID anti-inflammatory agents detected. Combining these increases stomach ulcer and cardiovascular strain.',
  },
];
